version: "3"
services:
  database:
    container_name: database
    image: postgres:16
    environment:
      POSTGRES_USER: superuser
      POSTGRES_PASSWORD: p@ssw0rd
      POSTGRES_DB: tme
    ports:
      - "5432:5432"

  redis_cache:
    container_name: cache_service
    image: redis:7.2
    ports:
      - "6379:6379"
